[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["cd backend && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd backend && npm start" 