[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend && npm install --production --no-optional"]

[phases.build]
cmds = ["cd backend && npm run verify"]

[start]
cmd = "cd backend && npm start" 