[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.npm"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start" 